image: gcc

build:
  stage: build
  before_script:
     - apt update && apt -y install make cmake
     - apt -y install llvm-9-dev libclang-common-9-dev clang
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/malinc
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      cache:
         paths:
           - "build/"

# run tests using the binary built before
# test if assign.ma compiles
test:
  stage: test
  before_script:
    - apt -y install llvm-9 libclang-common-9-dev clang
  script:
    - ./build/malinc -f test/assign.ma
