image: registry.gitlab.com/jeyrunner/malin-lang/ci-build-container

build:
  stage: build
  #before_script:
  #   - apt update && apt -y install make cmake
  #   - apt -y install llvm-9-dev libclang-common-9-dev clang
  script:
    - mkdir -p build
    - cd build
    - cmake -DDEP_LLVM_LINK_SHARED=OFF ..
    - make
    - cpack -G "DEB;STGZ;TGZ"
  artifacts:
    paths:
      - "build/malinc"
      - "build/std/c/libmalinCGlue.a"
      - "build/malinc-*.deb"
      - "build/malinc-*.sh"
      - "build/malinc-*.tar*"
  cache:
      paths:
       # - "build/"
        - "/root/.hunter/"

# run tests using the binary built before
# test if assign.ma compiles
test:
  stage: test
  script:
    - ./build/malinc -f test/assign.ma --not-create-object-file
